[project]
name = "phonopy-spectroscopy"
version = "0.1.0"
description = "Phonopy-Spectroscopy: A library for simulating vibrational spectroscopy"
authors = [
    { name = "Trace Bivens", email = "trace.bivens@example.com" }
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyyaml",
    "pandas",
    "h5py",
    "phonopy",
]
readme = "README.md"
license = { text = "BSD-3-Clause" }

[project.scripts]
phonopy-raman = "spectroscopy.cli.main_raman:main"
phonopy-ir = "spectroscopy.cli.main_ir:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
phonopy-spectroscopy = { path = ".", editable = true }

[tool.pixi.package]
run-dependencies = { phonopy = "*", numpy = "*", scipy = "*", pandas = "*", pyyaml = "*", h5py = "*" }
name = "phonopy-spectroscopy"
host-dependencies = { setuptools = "*" }

[tool.pixi.package.build]
  backend = { name = "pixi-build-python", version = "*" }
  channels = ["https://prefix.dev/conda-forge"]

[tool.setuptools.package-dir]
"" = "lib"

[tool.setuptools.packages.find]
where = ["lib"]

[tool.pixi.tasks]
ir-legacy = "python scripts/phonopy-ir"
raman-legacy = "python scripts/phonopy-raman"
test = "python -m unittest discover tests"
